name: ZeroLend
icon: logo.png
category: Money Market
metadata:
  pt:
    - chainId: 1
      address: '0x332a8ee60edff0a11cf3994b1b846bbc27d3dcd6'
      integrationUrl: >-
        https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0x332a8ee60edff0a11cf3994b1b846bbc27d3dcd6&marketName=proto_mainnet_btc_v3
      description: PT leverage looping through ZeroLend by using the PT as collateral
    - chainId: 1
      address: '0xb997b3418935a1df0f914ee901ec83927c1509a0'
      integrationUrl: >-
        https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0xb997b3418935a1df0f914ee901ec83927c1509a0&marketName=proto_mainnet_btc_v3
      description: PT leverage looping through ZeroLend by using the PT as collateral
    - chainId: 1
      address: '0x44A7876cA99460ef3218bf08b5f52E2dbE199566'
      integrationUrl: >-
        https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0x44a7876ca99460ef3218bf08b5f52e2dbe199566&marketName=proto_mainnet_btc_v3
      description: PT leverage looping through ZeroLend by using the PT as collateral
    - chainId: 1
      address: '0xEc5a52C685CC3Ad79a6a347aBACe330d69e0b1eD'
      integrationUrl: >-
        https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0xec5a52c685cc3ad79a6a347abace330d69e0b1ed&marketName=proto_mainnet_btc_v3
      description: PT leverage looping through ZeroLend by using the PT as collateral
    - chainId: 1
      address: '0xe00bd3df25fb187d6abbb620b3dfd19839947b81'
      integrationUrl: >-
        https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0xe00bd3df25fb187d6abbb620b3dfd19839947b81&marketName=proto_mainnet_rwa_v3
      description: PT leverage looping through ZeroLend by using the PT as collateral
    - chainId: 1
      address: '0x5bae9a5d67d1ca5b09b14c91935f635cfbf3b685'
      integrationUrl: >-
        https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0x5bae9a5d67d1ca5b09b14c91935f635cfbf3b685&marketName=proto_mainnet_rwa_v3
      description: PT leverage looping through ZeroLend by using the PT as collateral
    - chainId: 1
      address: '0x8a47b431a7d947c6a3ed6e42d501803615a97eaa'
      integrationUrl: >-
        https://app.zerolend.xyz/reserve-overview/?underlyingAsset=0x8a47b431a7d947c6a3ed6e42d501803615a97eaa&marketName=proto_mainnet_rwa_v3
      description: PT leverage looping through ZeroLend by using the PT as collateral
  yt: []
  lp: []
